import { StartupCardType } from "@/lib/types/startupCard.types";

export const posts: StartupCardType[] = [
  {
    _createdAt: "2025-05-01",
    views: 60,
    _id: 1,
    author: {
      _id: 101,
      name: "Jane Doe",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    description: "This is a brief description of the robot project.",
    image: "https://picsum.photos/seed/startup1/600/400",
    category: "Robots",
    title: "Robots title",
  },
  {
    _createdAt: "2025-04-30",
    views: 87,
    _id: 2,
    author: {
      _id: 102,
      name: "Alan Smith",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    description: "A look into eco-friendly tech gadgets.",
    image: "https://picsum.photos/seed/startup2/600/400",
    category: "Technology",
    title: "Green Tech Trends",
  },
  {
    _createdAt: "2025-04-29",
    views: 120,
    _id: 3,
    author: {
      _id: 103,
      name: "Nina Patel",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    description: "Exploring the future of AI integration.",
    image: "https://picsum.photos/seed/startup3/600/400",
    category: "AI",
    title: "AI in Everyday Life",
  },
  {
    _createdAt: "2025-04-28",
    views: 45,
    _id: 4,
    author: {
      _id: 104,
      name: "Liam Chen",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    description: "Top 10 JavaScript frameworks in 2025.",
    image: "https://picsum.photos/seed/startup4/600/400",
    category: "Programming",
    title: "JavaScript Frameworks",
  },
  {
    _createdAt: "2025-04-27",
    views: 30,
    _id: 5,
    author: {
      _id: 105,
      name: "Olivia Brown",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    description: "How blockchain is transforming finance.",
    image: "https://picsum.photos/seed/startup5/600/400",
    category: "Finance",
    title: "Blockchain in Banking",
  },
  {
    _createdAt: "2025-04-26",
    views: 95,
    _id: 6,
    author: {
      _id: 106,
      name: "Carlos Rivera",
      avatar: "https://i.pravatar.cc/150?img=6",
    },
    description: "Beginner tips for learning React.",
    image: "https://picsum.photos/seed/startup6/600/400",
    category: "Web Development",
    title: "Getting Started with React",
  },
  {
    _createdAt: "2025-04-25",
    views: 10,
    _id: 7,
    author: {
      _id: 107,
      name: "Emily Zhao",
      avatar: "https://i.pravatar.cc/150?img=7",
    },
    description: "The impact of automation on jobs.",
    image: "https://picsum.photos/seed/startup7/600/400",
    category: "Economy",
    title: "Automation and Employment",
  },
  {
    _createdAt: "2025-05-02",
    views: 200,
    _id: 8,
    author: {
      _id: 108,
      name: "Mohamed Ali",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
    description: "Latest breakthroughs in quantum computing.",
    image: "https://picsum.photos/seed/startup8/600/400",
    category: "Science",
    title: "Quantum Computing 2025",
  },
];
